### ISSUE TITLE
Hass.io is not starting with tensorflow enabled

### ISSUE THREAD

**Issue by MTrab** [hunterjm/hassio-addons#48]
I'm on .94.4 Home Assistant (as hass.io)
I'm trying to integrate tensorflow, but when starting after using this add-on with the following config, Home Assistant just hangs - no errors in log related to tensorflow.
As soon as I remove tensorflow from config, and restart, Home Assistant starts as supposed.

```
image_processing:
  - platform: tensorflow
    source:
      - entity_id: camera.frontdoor
      - entity_id: camera.hall
    file_out:
      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      graph: /config/tensorflow/model/frozen_inference_graph.pb
      categories:
        - category: person
```

Any ideas?
