### ISSUE TITLE
Docker Compose version?

### ISSUE THREAD

**Issue by mike391** [hunterjm/hassio-addons#50]
Is it possible to create a docker-compose version of those of u without Hass.io can use this awesome addon too?

**Comment by webdjoe** [comment]
You can use the dockerfile from the Xbox-python-rest repo and just have
compose build it. I have it running that way. If you plan to use the device
discovery part of it (not needed for the HA component), you have to set the
network mode as host

**Comment by mike391** [comment]
Got it working:
Docker-compose.yaml for future reference (ill make a PR if you guys want):
```
version: '2'

services:
  smartglass:
    network_mode: "host"
    restart: unless-stopped
    container_name: smartglass
    image: openxbox/xbox-smartglass-rest
    volumes:
      - /srv/dev-disk-by-label-RAID/Docker/.config/smartglass:/root/.local/share/xbox
```
